name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run PHP-CS-Fixer
        run: |
          php vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --format=txt --diff --dry-run --using-cache=no --verbose

      - name: Run PHPStan
        run: |
          php vendor/bin/phpstan analyse -c phpstan.neon
